def get_tickets():
    tickets = [
        {
            "id": 1,
            "title": "Printer not working",
            "description": "Printer in downstairs office is not connecting to my PC",
            "customer_name": "Rachael Green",
            "agent_id": 2,
            "created_at": "2026-05-02 14:00",
        },
        {
            "id": 2,
            "title": "Email issue",
            "description": "Outlook is not sending my messages, keep getting stuff in the outbox",
            "customer_name": "Mark Smith",
            "agent_id": 3,
            "created_at": "2026-05-02 16:20",
        },
        {
            "id": 3,
            "title": "Shared Drive Issue",
            "description": "My shared drives have a red x next to them",
            "customer_name": "Kate Whisby",
            "agent_id": 5,
            "created_at": "2026-05-02 15:50",
        },
        {
            "id": 4,
            "title": "VPN not connecting",
            "description": "Cannot connect to company VPN from home, error code 800",
            "customer_name": "James Thornton",
            "agent_id": 2,
            "created_at": "2026-05-02 16:00",
        },
        {
            "id": 5,
            "title": "Password reset request",
            "description": "Locked out of my account after too many attempts",
            "customer_name": "Sarah Collins",
            "agent_id": 3,
            "created_at": "2026-05-02 09:30",
        },
        {
            "id": 6,
            "title": "Monitor flickering",
            "description": "Second monitor keeps flickering, tried different cable",
            "customer_name": "Tom Bradley",
            "agent_id": None,
            "created_at": "2026-05-02 15:00",
        },
        {
            "id": 7,
            "title": "Teams not loading",
            "description": "Microsoft Teams stuck on loading screen since this morning",
            "customer_name": "Emma Walsh",
            "agent_id": None,
            "created_at": "2026-05-02 10:15",
        },
        {
            "id": 8,
            "title": "Keyboard not working",
            "description": "Several keys on keyboard stopped responding",
            "customer_name": "David Park",
            "agent_id": None,
            "created_at": "2026-05-02 13:30",
        },
        {
            "id": 9,
            "title": "Software installation request",
            "description": "Need Adobe Acrobat installed for new project",
            "customer_name": "Lucy Henderson",
            "agent_id": 4,
            "created_at": "2026-05-02 11:00",
        },
        {
            "id": 10,
            "title": "Slow computer",
            "description": "PC takes 20 minutes to boot up, very slow all day",
            "customer_name": "Chris Morgan",
            "agent_id": None,
            "created_at": "2026-05-02 09:44",
        },
        {
            "id": 11,
            "title": "No internet access",
            "description": "Cannot access any websites, other devices on same network work fine",
            "customer_name": "Fiona Clarke",
            "agent_id": 5,
            "created_at": "2026-05-02 11:45",
        },
        {
            "id": 12,
            "title": "Outlook calendar sync issue",
            "description": "Calendar not syncing with phone, missing meetings",
            "customer_name": "Ryan Peters",
            "agent_id": 2,
            "created_at": "2026-05-02 09:30",
        },
        {
            "id": 13,
            "title": "Printer out of toner",
            "description": "Upstairs printer showing toner empty message",
            "customer_name": "Amanda Foster",
            "agent_id": 3,
            "created_at": "2026-05-02 16:00",
        },
        {
            "id": 14,
            "title": "File permissions issue",
            "description": "Cannot access shared folder I had access to last week",
            "customer_name": "Ben Whitfield",
            "agent_id": 4,
            "created_at": "2026-05-02 10:00",
        },
        {
            "id": 15,
            "title": "New laptop setup",
            "description": "Need new laptop configured before Monday",
            "customer_name": "Natalie Simpson",
            "agent_id": None,
            "created_at": "2026-05-02 12:12",
        },
        {
            "id": 16,
            "title": "Spam emails",
            "description": "Receiving large volume of spam emails since yesterday",
            "customer_name": "George Hammond",
            "agent_id": 4,
            "created_at": "2026-05-02 14:13",
        },
        {
            "id": 17,
            "title": "Projector not displaying",
            "description": "Boardroom projector not detecting laptop input",
            "customer_name": "Claire Dixon",
            "agent_id": 2,
            "created_at": "2026-05-02 15:16",
        },
        {
            "id": 18,
            "title": "OneDrive sync error",
            "description": "Files not syncing to OneDrive, red cross on taskbar icon",
            "customer_name": "Steven Ward",
            "agent_id": None,
            "created_at": "2026-05-02 15:30",
        },
    ]
    return tickets
